name = "moetv"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[ d1_databases ]]
binding = "DB"
database_name = "moetv"
database_id = "6be2000f-f70e-4db2-9c2a-6f67e4d48f39"
migrations_dir = "drizzle"